### ISSUE TITLE
Add splash screen

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Prega#1]
Build and add a basic splash screen according to the figma design

Refer the [Figma File](https://www.figma.com/file/OAyBDXF2jlJKtNcYVLSFve/Prega.io?node-id=0%3A1)

**Comment by FoxxPratikSau** [comment]
Hey @Roshaen can I work on this issue?

**Comment by Roshaen** [comment]
Ya sure go ahead
Ping me on discord for google-services.json 
username : ```youHaveMe#9967```
Feel free to ask any doubts 😊
