### ISSUE TITLE
Onboarding screens

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Prega#2]
Add onboarding screens after first signup
Refer [figma file](https://www.figma.com/file/OAyBDXF2jlJKtNcYVLSFve/Prega.io?node-id=0%3A1)

**Comment by sanchitpandey** [comment]
Hi, is this project open for contribution?

**Comment by CodeSadhu** [comment]
@Roshaen I can take this up

**Comment by devtayade** [comment]
i really want to improve All anboarding screen, can you please assign it to me ?

**Comment by samitkapoor** [comment]
@Roshaen May I work on this issue?

**Comment by Roshaen** [comment]
Hii @sanchitpandey 
As you reached to the issue first so I can assign this issue to you?
If you really want to do it let me know else this issue will be assigned to others

**Comment by sanchitpandey** [comment]
Yes, I can assign it to me.

**Comment by sanchitpandey** [comment]
You*

**Comment by Roshaen** [comment]
@sanchitpandey cool go ahead
Ping me on discord to get google-services.json
username: ```youHaveMe#9967```

**Comment by insfirred** [comment]
Hi @Roshaen I want to work on this issue, but where are the screens in figma file?

**Comment by Roshaen** [comment]
Hello @insfirred this issue is already assigned
Please check out other issues or other repos
