### ISSUE TITLE
Edit docs

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Prega#3]
### UI
![edit_docs](https://user-images.githubusercontent.com/58213083/193326238-0b6f665c-6a67-4865-a434-e14b7e0551cc.png)

User should able to edit the docs details uploaded previously

**Comment by Omegaviv** [comment]
Hey @Roshaen  I would like to work on this screen, please assign it to me

**Comment by Roshaen** [comment]
Ya sure go ahead
Ping me on discord for google-services.json
username : youHaveMe#9967
Feel free to ask any doubts 😊

**Comment by Omegaviv** [comment]
I already have pinged you, please check

**Comment by Roshaen** [comment]
I have sent you that.
All the best🎉
