### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Prega#39]
### Description

+ Update `README.md`.
+ Add [Roshan Kumar](https://github.com/roshaen) as a maintainer in the readme, as it is done in [this](https://github.com/Clueless-Community/web-ui-kit) one.

**Comment by DevBhupendra** [comment]
How to add photo??

**Comment by Luckshya1210** [comment]
Hey! can I work on this issue?

**Comment by Luckshya1210** [comment]
> Hey! can I work on this issue?

@Roshaen pls assign me this issue!

**Comment by Roshaen** [comment]
@Luckshya1210  sure go ahead

**Comment by Luckshya1210** [comment]
@Roshaen I have raised a PR . Kindly review!
