### ISSUE TITLE
Tips page

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Prega#5]
Currently the tips screen is static and uses hardcoded data
It can be made dynamic by scrapping data from the web and update the UI according to it.

Refer [figma file](https://www.figma.com/file/OAyBDXF2jlJKtNcYVLSFve/Prega.io?node-id=0%3A1) for design

**Comment by CodeSadhu** [comment]
@Roshaen I'd like to take this up. Just one thing - I didn't find any screens in figma for this specific issue.

**Comment by Roshaen** [comment]
Hey @CodeSadhu I have assigned to another issue, do check that

**Comment by gautamjain09** [comment]
@Roshaen I'd like to take this issue. Just on doubt - I didn't find any specific design file for tips section.

**Comment by Roshaen** [comment]
Hey @gautamjain09 you can work on this issue
The design should look like this :
![photo_2022-10-02_15-55-40](https://user-images.githubusercontent.com/58213083/193449450-daa83078-d34d-47b0-94b8-9b5a098e5934.jpg)

**Comment by Roshaen** [comment]
Hey @gautamjain09 share your progress

**Comment by Roshaen** [comment]
youHaveMe#9967 @gautamjain09
