### ISSUE TITLE
Share page

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Prega#6]
Improve UI of share to doctor page
Refer to [figma file](https://www.figma.com/file/OAyBDXF2jlJKtNcYVLSFve/Prega.io?node-id=0%3A1) for design

**Comment by CodeSadhu** [comment]
I'm ready to take this up @Roshaen

**Comment by Roshaen** [comment]
Alright
Ping me on discord for google-services.json
username : ```youHaveMe#9967```

**Comment by Roshaen** [comment]
Hey @CodeSadhu Can you share your progress?

**Comment by Roshaen** [comment]
This issue is still open for anyone

**Comment by gautamjain09** [comment]
> This issue is still open for anyone

I will like to take this Issue

**Comment by Roshaen** [comment]
okay go on
Assigning...
